### ISSUE TITLE
问一下 机制 .....

### ISSUE THREAD

**Issue by a308667911** [Chen2226/PotPlayer_Subtitle_Translate#1]
我看 报错也能用

填写了 id key ，走的线路是 你的 服务器 ，是 必须 经过 你 服务器 中转 吗？

看了一下 记录，没有消耗 我账号 的 翻译字符量，难道是 走了你的账号 字符量？

**Comment by Chen2226** [comment]
报错不是返回报错信息吗
是的，必须经过我提供的api中转
是控制台延迟统计，有些延迟一两个小时，有些要隔天好像是
